# Ruff
[tool.ruff]
target-version = "py311"

[tool.ruff.format]
line-ending = "lf"


# Pyright
[tool.pyright]
exclude = ["**/node_modules",
    "**/__pycache__",
    "**/venv"
]
venvPath = "venv"

reportMissingImports = false
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"


