"""change PHONE_NUMBER length from 11 to 12

Revision ID: 036c8fa8fe33
Revises: c95585125030
Create Date: 2023-12-24 19:57:51.410631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036c8fa8fe33'
down_revision: Union[str, None] = 'c95585125030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
