"""change PHONE_NUMBER length from 11 to 12

Revision ID: 04f590136c48
Revises: 71b33a741a2a
Create Date: 2023-12-04 08:08:12.253682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f590136c48'
down_revision: Union[str, None] = '71b33a741a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
