"""change PHONE_NUMBER length from 11 to 12

Revision ID: 06cb70ecfa8f
Revises: 093c51828c6a
Create Date: 2023-12-24 19:13:12.474550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cb70ecfa8f'
down_revision: Union[str, None] = '093c51828c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
