"""change PHONE_NUMBER length from 11 to 12

Revision ID: 08d9f5850a78
Revises: 68df60cd59b4
Create Date: 2023-12-24 19:20:08.902506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d9f5850a78'
down_revision: Union[str, None] = '68df60cd59b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
