"""change PHONE_NUMBER length from 11 to 12

Revision ID: 093c51828c6a
Revises: 9efff2c26067
Create Date: 2023-12-24 19:12:32.433883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093c51828c6a'
down_revision: Union[str, None] = '9efff2c26067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
