"""change PHONE_NUMBER length from 11 to 12

Revision ID: 097437690f19
Revises: 0fd09330316f
Create Date: 2023-11-18 06:43:56.210650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097437690f19'
down_revision: Union[str, None] = '0fd09330316f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
