"""change PHONE_NUMBER length from 11 to 12

Revision ID: 0a441c6ebcc0
Revises: 097437690f19
Create Date: 2023-11-18 06:47:26.263568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a441c6ebcc0'
down_revision: Union[str, None] = '097437690f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
