"""change PHONE_NUMBER length from 11 to 12

Revision ID: 0cbf75f04ef9
Revises: ef2a8b5c68cd
Create Date: 2023-12-04 07:06:32.082260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbf75f04ef9'
down_revision: Union[str, None] = 'ef2a8b5c68cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
