"""change PHONE_NUMBER length from 11 to 12

Revision ID: 0f5156204011
Revises: d3c8cd315394
Create Date: 2023-12-04 08:05:04.117254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5156204011'
down_revision: Union[str, None] = 'd3c8cd315394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
