"""change PHONE_NUMBER length from 11 to 12

Revision ID: 0fd09330316f
Revises: 8613508be10e
Create Date: 2023-11-18 06:41:13.308825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd09330316f'
down_revision: Union[str, None] = '8613508be10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
