"""change PHONE_NUMBER length from 11 to 12

Revision ID: 1036d83e03e6
Revises: e77ac5b7b18c
Create Date: 2023-12-24 20:05:38.142286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1036d83e03e6'
down_revision: Union[str, None] = 'e77ac5b7b18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
