"""change PHONE_NUMBER length from 11 to 12

Revision ID: 15d4c528b1c6
Revises: cf00219e4aaa
Create Date: 2023-11-18 08:09:51.484503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d4c528b1c6'
down_revision: Union[str, None] = 'cf00219e4aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
