"""change PHONE_NUMBER length from 11 to 12

Revision ID: 18257c3d4823
Revises: 15d4c528b1c6
Create Date: 2023-11-18 08:10:31.493101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18257c3d4823'
down_revision: Union[str, None] = '15d4c528b1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
