"""change PHONE_NUMBER length from 11 to 12

Revision ID: 1acdc015e8a4
Revises: 7c2914e64a8c
Create Date: 2023-12-24 18:24:03.447584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acdc015e8a4'
down_revision: Union[str, None] = '7c2914e64a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
