"""change PHONE_NUMBER length from 11 to 12

Revision ID: 28b718a2e10b
Revises: d1d01881dee3
Create Date: 2023-12-04 08:03:40.264676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b718a2e10b'
down_revision: Union[str, None] = 'd1d01881dee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
