"""change PHONE_NUMBER length from 11 to 12

Revision ID: 2a696f535644
Revises: 941f83a53722
Create Date: 2023-12-04 13:16:54.158560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a696f535644'
down_revision: Union[str, None] = '941f83a53722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
