"""change PHONE_NUMBER length from 11 to 12

Revision ID: 2b330b3d72c9
Revises: 12b833f4cb46
Create Date: 2023-11-18 07:47:05.085467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b330b3d72c9'
down_revision: Union[str, None] = '12b833f4cb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
