"""change PHONE_NUMBER length from 11 to 12

Revision ID: 30f8f8de7c51
Revises: 90a9610cff4f
Create Date: 2023-11-18 06:51:17.948913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f8f8de7c51'
down_revision: Union[str, None] = '90a9610cff4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
