"""change PHONE_NUMBER length from 11 to 12

Revision ID: 3180d9aea65d
Revises: 10cb34e3e81b
Create Date: 2023-12-04 07:09:04.644405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3180d9aea65d'
down_revision: Union[str, None] = '10cb34e3e81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
