"""change PHONE_NUMBER length from 11 to 12

Revision ID: 31ca29d230b3
Revises: a92d62a4176f
Create Date: 2023-12-24 17:00:09.764682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ca29d230b3'
down_revision: Union[str, None] = 'a92d62a4176f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
