"""change PHONE_NUMBER length from 11 to 12

Revision ID: 3b6662533db8
Revises: 67c252a62149
Create Date: 2023-11-18 07:07:31.813937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6662533db8'
down_revision: Union[str, None] = '67c252a62149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
