"""change PHONE_NUMBER length from 11 to 12

Revision ID: 3fbc5cffb4ed
Revises: d5890bbcc1fc
Create Date: 2023-12-24 19:34:49.795765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbc5cffb4ed'
down_revision: Union[str, None] = 'd5890bbcc1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
