"""change PHONE_NUMBER length from 11 to 12

Revision ID: 45b4057194f3
Revises: 7109734406bd
Create Date: 2023-12-04 08:11:29.812947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b4057194f3'
down_revision: Union[str, None] = '7109734406bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
