"""change PHONE_NUMBER length from 11 to 12

Revision ID: 4b4b74dfe029
Revises: d51fcf3f6391
Create Date: 2023-12-24 19:08:12.216953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4b74dfe029'
down_revision: Union[str, None] = 'd51fcf3f6391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
