"""change PHONE_NUMBER length from 11 to 12

Revision ID: 4ca944d6d5c7
Revises: dbaf297dc8d3
Create Date: 2023-12-24 08:43:03.680968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca944d6d5c7'
down_revision: Union[str, None] = 'dbaf297dc8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
