"""change PHONE_NUMBER length from 11 to 12

Revision ID: 540b28777caa
Revises: 1036d83e03e6
Create Date: 2023-12-24 20:16:46.073877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540b28777caa'
down_revision: Union[str, None] = '1036d83e03e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
