"""change PHONE_NUMBER length from 11 to 12

Revision ID: 54100f3b6db6
Revises: 3180d9aea65d
Create Date: 2023-12-04 07:09:30.837238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54100f3b6db6'
down_revision: Union[str, None] = '3180d9aea65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
