"""change PHONE_NUMBER length from 11 to 12

Revision ID: 5600b7c0e139
Revises: f68d73fc3823
Create Date: 2023-12-24 18:22:05.006087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5600b7c0e139'
down_revision: Union[str, None] = 'f68d73fc3823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
