"""change PHONE_NUMBER length from 11 to 12

Revision ID: 5b6fb6e86b62
Revises: 80f5d762898c
Create Date: 2023-12-24 20:01:56.514262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6fb6e86b62'
down_revision: Union[str, None] = '80f5d762898c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
