"""change PHONE_NUMBER length from 11 to 12

Revision ID: 67c252a62149
Revises: 30f8f8de7c51
Create Date: 2023-11-18 06:57:35.265727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c252a62149'
down_revision: Union[str, None] = '30f8f8de7c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
