"""change PHONE_NUMBER length from 11 to 12

Revision ID: 68df60cd59b4
Revises: 06cb70ecfa8f
Create Date: 2023-12-24 19:14:37.622385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68df60cd59b4'
down_revision: Union[str, None] = '06cb70ecfa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
