"""change PHONE_NUMBER length from 11 to 12

Revision ID: 7109734406bd
Revises: 04f590136c48
Create Date: 2023-12-04 08:10:02.795612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7109734406bd'
down_revision: Union[str, None] = '04f590136c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
