"""change PHONE_NUMBER length from 11 to 12

Revision ID: 71b33a741a2a
Revises: 0f5156204011
Create Date: 2023-12-04 08:07:02.147582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b33a741a2a'
down_revision: Union[str, None] = '0f5156204011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
