"""change PHONE_NUMBER length from 11 to 12

Revision ID: 78fd4d53faa3
Revises: 68684398c605
Create Date: 2023-12-04 08:02:38.395093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fd4d53faa3'
down_revision: Union[str, None] = '68684398c605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
