"""change PHONE_NUMBER length from 11 to 12

Revision ID: 7c2914e64a8c
Revises: 5600b7c0e139
Create Date: 2023-12-24 18:22:31.691448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2914e64a8c'
down_revision: Union[str, None] = '5600b7c0e139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
