"""change PHONE_NUMBER length from 11 to 12

Revision ID: 80f5d762898c
Revises: 036c8fa8fe33
Create Date: 2023-12-24 19:58:32.615082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f5d762898c'
down_revision: Union[str, None] = '036c8fa8fe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
