"""change PHONE_NUMBER length from 11 to 12

Revision ID: 8b4d3601d9f8
Revises: c538ac26baf7
Create Date: 2023-12-24 16:33:48.584749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4d3601d9f8'
down_revision: Union[str, None] = 'c538ac26baf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
