"""change PHONE_NUMBER length from 11 to 12

Revision ID: 8e9f148ace30
Revises: ab344765f6ba
Create Date: 2023-12-04 11:22:49.200267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9f148ace30'
down_revision: Union[str, None] = 'ab344765f6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
