"""change PHONE_NUMBER length from 11 to 12

Revision ID: 90a9610cff4f
Revises: 9c247f0b4cf6
Create Date: 2023-11-18 06:50:44.823360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a9610cff4f'
down_revision: Union[str, None] = '9c247f0b4cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
