"""change PHONE_NUMBER length from 11 to 12

Revision ID: 9156ab05384d
Revises: bb4079c28926
Create Date: 2023-12-24 20:04:40.380363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9156ab05384d'
down_revision: Union[str, None] = 'bb4079c28926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
