"""change PHONE_NUMBER length from 11 to 12

Revision ID: 9417e17b751a
Revises: 08d9f5850a78
Create Date: 2023-12-24 19:21:12.234783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9417e17b751a'
down_revision: Union[str, None] = '08d9f5850a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
