"""change PHONE_NUMBER length from 11 to 12

Revision ID: 941f83a53722
Revises: acb8d4301e40
Create Date: 2023-12-04 13:16:40.284776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941f83a53722'
down_revision: Union[str, None] = 'acb8d4301e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
