"""change PHONE_NUMBER length from 11 to 12

Revision ID: 9980a71b7447
Revises: 8e9f148ace30
Create Date: 2023-12-04 11:22:56.698230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9980a71b7447'
down_revision: Union[str, None] = '8e9f148ace30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
