"""change PHONE_NUMBER length from 11 to 12

Revision ID: 9c247f0b4cf6
Revises: 0a441c6ebcc0
Create Date: 2023-11-18 06:49:06.526102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c247f0b4cf6'
down_revision: Union[str, None] = '0a441c6ebcc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
