"""change PHONE_NUMBER length from 11 to 12

Revision ID: 9efff2c26067
Revises: 36ac3639f6e5
Create Date: 2023-12-24 19:09:43.596292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efff2c26067'
down_revision: Union[str, None] = '36ac3639f6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
