"""change PHONE_NUMBER length from 11 to 12

Revision ID: a84083d53292
Revises: 4ca944d6d5c7
Create Date: 2023-12-24 08:44:06.363215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84083d53292'
down_revision: Union[str, None] = '4ca944d6d5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
