"""change PHONE_NUMBER length from 11 to 12

Revision ID: a92d62a4176f
Revises: 1cc26f1f82d2
Create Date: 2023-12-24 16:59:52.266479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92d62a4176f'
down_revision: Union[str, None] = '1cc26f1f82d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
