"""change PHONE_NUMBER length from 11 to 12

Revision ID: ab344765f6ba
Revises: bfe3b7358c1f
Create Date: 2023-12-04 11:21:39.572449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab344765f6ba'
down_revision: Union[str, None] = 'bfe3b7358c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
