"""change PHONE_NUMBER length from 11 to 12

Revision ID: acb8d4301e40
Revises: 2f9dc80dce77
Create Date: 2023-12-04 13:15:37.189846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb8d4301e40'
down_revision: Union[str, None] = '2f9dc80dce77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
