"""change PHONE_NUMBER length from 11 to 12

Revision ID: b804e4dbf24d
Revises: 45b4057194f3
Create Date: 2023-12-04 11:19:19.821563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b804e4dbf24d'
down_revision: Union[str, None] = '45b4057194f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
