"""change PHONE_NUMBER length from 11 to 12

Revision ID: badbabeb25fb
Revises: 5b0a8d58fc18
Create Date: 2023-12-24 19:25:07.608245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'badbabeb25fb'
down_revision: Union[str, None] = '5b0a8d58fc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
