"""change PHONE_NUMBER length from 11 to 12

Revision ID: be9c9fe219c6
Revises: b804e4dbf24d
Create Date: 2023-12-04 11:19:36.192248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9c9fe219c6'
down_revision: Union[str, None] = 'b804e4dbf24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
