"""change PHONE_NUMBER length from 11 to 12

Revision ID: bfe3b7358c1f
Revises: be9c9fe219c6
Create Date: 2023-12-04 11:21:23.554170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe3b7358c1f'
down_revision: Union[str, None] = 'be9c9fe219c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
