"""change PHONE_NUMBER length from 11 to 12

Revision ID: c538ac26baf7
Revises: a84083d53292
Create Date: 2023-12-24 16:21:03.296008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c538ac26baf7'
down_revision: Union[str, None] = 'a84083d53292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
