"""change PHONE_NUMBER length from 11 to 12

Revision ID: c95585125030
Revises: e3108fefb38b
Create Date: 2023-12-24 19:56:57.626065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95585125030'
down_revision: Union[str, None] = 'e3108fefb38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
