"""change PHONE_NUMBER length from 11 to 12

Revision ID: cd7652d39338
Revises: 93bc2add2415
Create Date: 2023-11-18 07:42:13.119738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7652d39338'
down_revision: Union[str, None] = '93bc2add2415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
