"""change PHONE_NUMBER length from 11 to 12

Revision ID: cf00219e4aaa
Revises: 2b330b3d72c9
Create Date: 2023-11-18 08:08:33.916016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf00219e4aaa'
down_revision: Union[str, None] = '2b330b3d72c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
