"""change PHONE_NUMBER length from 11 to 12

Revision ID: d1d01881dee3
Revises: 78fd4d53faa3
Create Date: 2023-12-04 08:03:10.414576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d01881dee3'
down_revision: Union[str, None] = '78fd4d53faa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
