"""change PHONE_NUMBER length from 11 to 12

Revision ID: d3c8cd315394
Revises: 28b718a2e10b
Create Date: 2023-12-04 08:04:28.179798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c8cd315394'
down_revision: Union[str, None] = '28b718a2e10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
