"""change PHONE_NUMBER length from 11 to 12

Revision ID: d51fcf3f6391
Revises: 47debd66b985
Create Date: 2023-12-24 18:26:19.220322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51fcf3f6391'
down_revision: Union[str, None] = '47debd66b985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
