"""change PHONE_NUMBER length from 11 to 12

Revision ID: d7a81048a5cd
Revises: eadcef5cda06
Create Date: 2023-12-04 07:08:02.890937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a81048a5cd'
down_revision: Union[str, None] = 'eadcef5cda06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
