"""change PHONE_NUMBER length from 11 to 12

Revision ID: dbaf297dc8d3
Revises: 2a696f535644
Create Date: 2023-12-04 16:50:17.591468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaf297dc8d3'
down_revision: Union[str, None] = '2a696f535644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
