"""change PHONE_NUMBER length from 11 to 12

Revision ID: e023065edd84
Revises: 1175cf8c6f02
Create Date: 2023-11-18 07:37:47.631678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e023065edd84'
down_revision: Union[str, None] = '1175cf8c6f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
