"""change PHONE_NUMBER length from 11 to 12

Revision ID: e3108fefb38b
Revises: 3fbc5cffb4ed
Create Date: 2023-12-24 19:54:03.744891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3108fefb38b'
down_revision: Union[str, None] = '3fbc5cffb4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
