"""change PHONE_NUMBER length from 11 to 12

Revision ID: e551855b5178
Revises: f7ec0c0af8e6
Create Date: 2023-12-24 18:17:44.342217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e551855b5178'
down_revision: Union[str, None] = 'f7ec0c0af8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
