"""change PHONE_NUMBER length from 11 to 12

Revision ID: e77ac5b7b18c
Revises: 9156ab05384d
Create Date: 2023-12-24 20:05:28.173660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77ac5b7b18c'
down_revision: Union[str, None] = '9156ab05384d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
