"""change PHONE_NUMBER length from 11 to 12

Revision ID: eadcef5cda06
Revises: 0cbf75f04ef9
Create Date: 2023-12-04 07:07:08.099580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadcef5cda06'
down_revision: Union[str, None] = '0cbf75f04ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
