"""change PHONE_NUMBER length from 11 to 12

Revision ID: f68d73fc3823
Revises: e551855b5178
Create Date: 2023-12-24 18:20:16.895072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68d73fc3823'
down_revision: Union[str, None] = 'e551855b5178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
