"""change PHONE_NUMBER length from 11 to 12

Revision ID: f7ec0c0af8e6
Revises: d6a9b3351044
Create Date: 2023-12-24 18:16:00.091484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ec0c0af8e6'
down_revision: Union[str, None] = 'd6a9b3351044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
